### ISSUE TITLE
Problem trying to apply migration

### ISSUE THREAD

**Issue by clluiz** [platformatic/tutorial-movie-quotes-app#15]
I'm following the tutorial-movie-quotes-app but when I try to apply the 002.db.sql the app freezes and the migration is not applied.
 Here's what my console is showing:

![image](https://user-images.githubusercontent.com/1070968/205175468-7f655b6b-074a-42a2-bfad-14e9cc5fc09a.png)

I'm using node version 18.8.0 and npm 8.18.0

**Comment by simonplend** [comment]
> I'm following the tutorial-movie-quotes-app

Do you mean that you've cloned [this repository](https://github.com/platformatic/tutorial-movie-quotes-app) and are trying to run the applications?

If that's the case, you should run `npm install` and then `npm run dev` ([see the README](https://github.com/platformatic/tutorial-movie-quotes-app#setup)).

**Comment by simonplend** [comment]
The console output in the screenshot you've shared is a little confusing. It looks like output from npm and Platformatic DB have been combined somehow.

Have you tried manually applying the migration? With v0.9.0 of `platformatic`, run `npx platformatic db migrations apply`, for earlier versions run `npx platformatic db migrate`.

If your database gets into a weird state while following this tutorial, you can delete the `movie-quotes.sqlite` file, manually apply the migrations, and then run the seed script.

**Comment by clluiz** [comment]
I will try @simonplend . Thanks for the help!

**Comment by clluiz** [comment]
Solved.

**Comment by simonplend** [comment]
Great! What was the issue?

**Comment by clluiz** [comment]
In fact was a type in my migration file name. I wrote 002.db.sql rather than 002.do.sql. :neutral_face:

**Comment by simonplend** [comment]
Oh no! Glad you were able to find the problem though.

@mcollina I think it would be helpful to identify unrecognised migration files in the migrations directory i.e. ones with incorrect file extensions. I can see typos like this being a common issue and a big debugging time waste for folks. What do you think?
