### ISSUE TITLE
[frontend] Client side JavaScript isn't bundled when the Astro dev server starts

### ISSUE THREAD

**Issue by simonplend** [platformatic/tutorial-movie-quotes-app#3]
This affects the delete quote and like quote functionality. It appears to be an issue when using Astro with the [@astrojs/tailwind](https://www.npmjs.com/package/@astrojs/tailwind) integration.

Related Astro issue: [Script file isn't loaded on start astro dev when using tailwindcss](https://github.com/withastro/astro/issues/4217)

**Comment by simonplend** [comment]
I'm attempting to implement this workaround: https://github.com/withastro/astro/issues/4217#issuecomment-1221327619

My own workaround is to run the following command after starting the Astro dev server:

```
touch apps/movie-quotes-frontend/src/pages/index.astro
```

And then refresh the frontend quotes listing page in the web browser.

**Comment by mcollina** [comment]
The workaround is not really working for me.

**Comment by mcollina** [comment]
Nevermind, this was my bad.
